wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    start_time: 1701092601.018679
=======
    start_time: 1701191494.718955
>>>>>>> Stashed changes
=======
    start_time: 1701355468.190156
>>>>>>> Stashed changes
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 77
      3:
      - 2
<<<<<<< Updated upstream
<<<<<<< Updated upstream
=======
      - 7
      - 13
>>>>>>> Stashed changes
=======
      - 7
      - 13
>>>>>>> Stashed changes
      - 23
      4: 3.11.5
      5: 0.16.0
      6: 4.35.2
      8:
      - 1
      - 5
      13: linux-x86_64
<<<<<<< Updated upstream
<<<<<<< Updated upstream
DimeNet_model:
  desc: null
  value:
    act: swish
    cutoff: 5.0
    envelope_exponent: 5
    hidden_channels: 128
    node_class: 119
    num_after_skip: 2
    num_before_skip: 1
    num_bilinear: 8
    num_blocks: 6
    num_output_layers: 3
    num_radial: 6
    num_spherical: 7
    out_channels: 1
STK_path:
  desc: null
  value: /rds/general/user/cb1319/home/GEOM3D/STK_path/
SchNet_model:
  desc: null
  value:
    SchNet_cutoff: 10
    SchNet_num_filters: 128
    SchNet_num_gaussians: 51
    SchNet_num_interactions: 6
    SchNet_readout: mean
    edge_class: 5
    emb_dim: 128
    node_class: 119
    num_tasks: 1
batch_size:
  desc: null
  value: 128
database_name:
  desc: null
  value: stk_cyprien
dataset_path:
  desc: null
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/training/dataset.pt
dataset_path_frag:
  desc: null
  value: ''
=======
=======
>>>>>>> Stashed changes
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
STK_path:
  desc: null
  value: /rds/general/user/cb1319/home/GEOM3D/STK_path/
batch_size:
  desc: null
<<<<<<< Updated upstream
  value: 64
database_name:
  desc: null
  value: stk_mohammed_BO
>>>>>>> Stashed changes
=======
  value: 32
database_name:
  desc: null
  value: stk_mohammed_BO
>>>>>>> Stashed changes
df_precursor:
  desc: null
  value: calculation_data_precursor_071123_clean.pkl
df_total:
  desc: null
  value: df_total_subset_16_11_23.csv
emb_dim:
  desc: null
  value: 128
<<<<<<< Updated upstream
<<<<<<< Updated upstream
load_dataset:
  desc: null
  value: true
max_epochs:
  desc: null
  value: 3
=======
=======
>>>>>>> Stashed changes
max_epochs:
  desc: null
  value: 5
model_name:
  desc: null
  value: DimeNet
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
model_path:
  desc: null
  value: ''
name:
  desc: null
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  value: SchNet_target_1K_TEST_5e4lr
num_molecules:
  desc: null
  value: 1000
=======
  value: DimeNetPlusPlus_target_1K_TEST_5e4lr
num_molecules:
  desc: null
  value: 500
>>>>>>> Stashed changes
=======
  value: DimeNet_target_1K_TEST_5e4lr
num_molecules:
  desc: null
  value: 500
>>>>>>> Stashed changes
num_tasks:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 0
number_of_fragement:
  desc: null
  value: 6
pl_model_chkpt:
  desc: null
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/training/SchNet_target_1K_TEST_5e4lr/epoch=86-val_loss=0.54-other_metric===.00.ckpt
=======
  value: ''
>>>>>>> Stashed changes
=======
  value: ''
>>>>>>> Stashed changes
pymongo_client:
  desc: null
  value: mongodb://129.31.66.201/
running_dir:
  desc: null
<<<<<<< Updated upstream
<<<<<<< Updated upstream
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/training
=======
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/
>>>>>>> Stashed changes
=======
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/
>>>>>>> Stashed changes
save_dataset:
  desc: null
  value: true
seed:
  desc: null
  value: 42
train_ratio:
  desc: null
  value: 0.8
valid_ratio:
  desc: null
  value: 0.1
<<<<<<< Updated upstream
<<<<<<< Updated upstream
device:
  desc: null
  value: cuda
model:
  desc: null
  value:
    SchNet_cutoff: 10
    SchNet_num_filters: 128
    SchNet_num_gaussians: 51
    SchNet_num_interactions: 6
    SchNet_readout: mean
    edge_class: 5
    emb_dim: 128
    node_class: 119
    num_tasks: 1
=======
=======
>>>>>>> Stashed changes
load_dataset:
  desc: null
  value: true
dataset_path:
  desc: null
<<<<<<< Updated upstream
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/training/dataset.pt
=======
  value: /rds/general/user/cb1319/home/GEOM3D/Geom3D/training/DimeNetPlusPlus_target_1K_TEST_5e4lr/500dataset.pt
>>>>>>> Stashed changes
dataset_path_frag:
  desc: null
  value: ''
model:
  desc: null
  value:
    node_class: 119
<<<<<<< Updated upstream
    hidden_channels: 30
    out_channels: 1
    num_blocks: 4
    int_emb_size: 64
    basis_emb_size: 8
    out_emb_channels: 128
    num_spherical: 7
    num_radial: 6
    cutoff: 5.0
=======
    hidden_channels: 20
    out_channels: 1
    num_blocks: 6
    num_bilinear: 8
    num_spherical: 7
    num_radial: 6
    cutoff: 3.0
>>>>>>> Stashed changes
    envelope_exponent: 5
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
device:
  desc: null
  value: cuda
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
